# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-233b8b6f-1848-4b0c-b3ce-a6494b255d27";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-233b8b6f-1848-4b0c-b3ce-a6494b255d27".device = "/dev/disk/by-uuid/233b8b6f-1848-4b0c-b3ce-a6494b255d27";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/951A-5081";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-d9299f58-f5e1-4243-b5fb-eb2e5f6ac918"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
