# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, user, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-9f594ea2-f702-4867-a1b9-335d1d3385ff";
      fsType = "ext4";
    };

  # sdb2 — root filesystem
  boot.initrd.luks.devices."luks-9f594ea2-f702-4867-a1b9-335d1d3385ff".device = "/dev/disk/by-uuid/9f594ea2-f702-4867-a1b9-335d1d3385ff";
  # sdb3 — swap
  boot.initrd.luks.devices."luks-2dd32cf4-aa21-4589-aee3-55699ee4a62e".device = "/dev/disk/by-uuid/2dd32cf4-aa21-4589-aee3-55699ee4a62e";
  # sda1 — data drive (/home/${user}/data)
  boot.initrd.luks.devices."luks-2e2a1b52-497f-43c3-b213-5cf61a4220a7".device = "/dev/disk/by-uuid/2e2a1b52-497f-43c3-b213-5cf61a4220a7";

  fileSystems."/home/${user}/data" =
    { device = "/dev/mapper/luks-2e2a1b52-497f-43c3-b213-5cf61a4220a7";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2346-DA8D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-2dd32cf4-aa21-4589-aee3-55699ee4a62e"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  services.xserver.videoDrivers = [ "nvidia" ];

  hardware.graphics.enable = true;

  hardware.nvidia = {
    modesetting.enable = true;
    powerManagement.enable = false;
    open = false; # Set to true only if you want the experimental open-source kernel module
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };

}
