# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-10815544-234f-422b-bd70-acaa7b2dbe6a";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-10815544-234f-422b-bd70-acaa7b2dbe6a".device = "/dev/disk/by-uuid/10815544-234f-422b-bd70-acaa7b2dbe6a";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BA47-FA9D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-044569af-44d1-4913-bace-ff6ffe4bf0ef"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
